### ISSUE TITLE
"About Author Tools" Webpage, bug reporting

### ISSUE THREAD

**Issue by klensin** [ietf-tools/ietf-at-ui#102]
Hi.
When one goes to https://author-tools.ietf.org/about.html#howto-report-bugs, there are three entries for bugs and feature requests involving the web site,  bugs and feature requests involving the API, and "General discussions about IETF Author Tools and other IETF tools...".   As an aid to the easily confused, if the intention is that bugs in some of the tools be reported to the latter address, it would be helpful to edit that last category to say so, e.g., change the sentence to read "Bug reports, feature requests, and general discussions about...".    For those reporting actual bugs, providing a mechanism for moving reports about problems with tools to go through some sort of tracker would seem (at least to me) to be a good idea.

thanks.

**Comment by kesara** [comment]
I will try to make use of GitHub issue templates similar to datatracker.
Also, I will provide a single place to report issues because having two projects can confusing, tools team have the ability to transfer issues to the correct project once an issue is created.
Hope these changes might make things less confusing.

**Comment by kesara** [comment]
OBE
